module

/-
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with `1` and `2`, the first `10` terms will be:
`1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...`
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
-/

def fibonacciNumbersLessThan
  (n : Nat)
  :=
  Id.run do
  if n = 0 ∨ n = 1 then return #[]
  if n = 2 then return #[1]

  let mut fibonacciNumbers := #[1, 2]
  let mut previous := 1
  let mut current := 2

  while previous + current < n do
    let new := previous + current
    fibonacciNumbers := fibonacciNumbers.push new
    previous := current
    current := new

  fibonacciNumbers

#eval fibonacciNumbersLessThan 4_000_000
  |>.filter (· % 2 = 0)
  |>.sum
